module.exports = {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#001e40',
          container: '#003366',
          fixed: '#d5e3ff',
          'fixed-dim': '#a7c8ff',
        },
        secondary: {
          DEFAULT: '#28628f',
          container: '#97ccfe',
          fixed: '#cee5ff',
          'fixed-dim': '#97ccfe',
        },
        tertiary: {
          DEFAULT: '#161e31',
          container: '#2b3347',
          fixed: '#dae2fd',
          'fixed-dim': '#bec6e0',
        },
        surface: {
          DEFAULT: '#f7f9fb',
          dim: '#d8dadc',
          bright: '#f7f9fb',
          variant: '#e0e3e5',
          tint: '#3a5f94',
          container: '#eceef0',
          'container-lowest': '#ffffff',
          'container-low': '#f2f4f6',
          'container-high': '#e6e8ea',
          'container-highest': '#e0e3e5',
        },
        background: '#f7f9fb',
        outline: {
          DEFAULT: '#737780',
          variant: '#c3c6d1',
        },
        error: {
          DEFAULT: '#ba1a1a',
          container: '#ffdad6',
        },
        'on-primary': '#ffffff',
        'on-primary-container': '#799dd6',
        'on-primary-fixed': '#001b3c',
        'on-primary-fixed-variant': '#1f477b',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#175683',
        'on-secondary-fixed': '#001d32',
        'on-secondary-fixed-variant': '#004a75',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#949bb4',
        'on-tertiary-fixed': '#131b2e',
        'on-tertiary-fixed-variant': '#3f465c',
        'on-surface': '#191c1e',
        'on-surface-variant': '#43474f',
        'on-background': '#191c1e',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'inverse-primary': '#a7c8ff',
      },
      fontFamily: {
        sans: ['Public Sans', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
